### ISSUE TITLE
2025-05-18  Blackbox Exporter probe 실패 (Prod FE) — HTTP/2.0 호환성 문제

### ISSUE THREAD

**Issue by flydog98** [100-hours-a-week/16-Hot6-wiki#273]
# 2025-05-18  Blackbox Exporter probe 실패 (Prod FE) — HTTP/2.0 호환성 문제

## 🧭 Context
- 대상 도메인: `https://onthe-top.com` (prod FE)
- 구조: `CloudFront → S3`
- 모니터링 대상: Prometheus Blackbox Exporter

## 🔥 증상
- `probe_success{instance="prod-frontend"}` = 0
- Prometheus Alert: `ProdFrontendHttpsDown` firing
- 서비스는 실제로 정상 동작 중 (curl, 브라우저 모두 정상 200)

## 🔍 조사 로그 (Blackbox Exporter debug output)

```
ts=2025-05-18T09:59:26Z level=info msg="Received HTTP response" status_code=200
ts=2025-05-18T09:59:26Z level=error msg="Invalid HTTP version number" version=HTTP/2.0
ts=2025-05-18T09:59:26Z level=error msg="Probe failed"
probe_http_status_code 200
probe_http_version 2
probe_success 0
```

## 🔍 원인 분석
- CloudFront는 클라이언트가 지원할 경우 **HTTP/2.0을 기본 사용**
- Blackbox Exporter 설정:
  
  ```yaml
  valid_http_versions: ["HTTP/1.1"]
  ```

- 따라서 응답이 200이어도, 버전 불일치로 실패 처리됨

### dev 환경 (`https://dev.onthe-top.com`)
- 구조: `Nginx → Spring FE`
- HTTP 응답 버전: HTTP/1.1
- Blackbox 설정과 호환되어 정상 probe 성공

### prod 환경 (`https://onthe-top.com`)
- 구조: `CloudFront (TLS termination)`
- HTTP 응답 버전: HTTP/2.0
- 설정 불일치로 실패

### 🔧 설정 수정

blackbox.yml:

```yaml
modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      method: GET
      valid_http_versions: ["HTTP/1.1", "HTTP/2", "HTTP/2.0"]
      tls_config:
        insecure_skip_verify: false
```

### 🔄 재시작

```bash
sudo systemctl restart blackbox-exporter
```

또는 Docker:

```bash
docker restart blackbox-exporter
```

## ✅ 결과

- 이후 `probe_success{instance="prod-frontend"}` = 1로 정상 수집
- 알람 해제
- dev/prod 환경에서 HTTP 버전 차이 존재하지만, 모듈 설정으로 호환 가능하게 유지

## 🧠 회고

| 항목 | 교훈 |
|------|------|
| CloudFront의 HTTP/2 기본 설정 | 의도하지 않은 probe 실패를 유발할 수 있음 |
| Blackbox Exporter의 HTTP 버전 처리 | 매우 엄격 — 응답 200이어도 버전 mismatch 시 실패 |
| dev/prod 차이 고려 | 테스트 환경에서는 단순한 HTTP/1.1이 오히려 디버깅에 유리함 |
